// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebRazorPages.Data;

#nullable disable

namespace WebRazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230521130937_AddRazorCategoryToDb")]
    partial class AddRazorCategoryToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebRazorPages.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 5, 19, 20, 9, 37, 814, DateTimeKind.Local).AddTicks(8522),
                            GroupId = 2,
                            Login = "boris2020razror",
                            Password = "123boris123rz",
                            UserState = "Blocked"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 5, 11, 20, 9, 37, 814, DateTimeKind.Local).AddTicks(8539),
                            GroupId = 1,
                            Login = "superadminrazor",
                            Password = "adminadmin1rz",
                            UserState = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 5, 18, 20, 9, 37, 814, DateTimeKind.Local).AddTicks(8541),
                            GroupId = 2,
                            Login = "serejenkarazor",
                            Password = "imserge222rz",
                            UserState = "Blocked"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
