// <auto-generated />
using System;
using AspCore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspCore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230526080651_AddNewTableUsersGroup")]
    partial class AddNewTableUsersGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 5, 24, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9577),
                            GroupId = 2,
                            Login = "boris2020",
                            Password = "123boris123",
                            UserState = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 5, 16, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9596),
                            GroupId = 1,
                            Login = "superadmin",
                            Password = "adminadmin1",
                            UserState = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 5, 23, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9598),
                            GroupId = 2,
                            Login = "serejenka",
                            Password = "imserge222",
                            UserState = "Blocked"
                        });
                });

            modelBuilder.Entity("AspCore.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Active",
                            CreatedDate = new DateTime(2023, 5, 24, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9766),
                            Description = "CSGO Lovers"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Blocked",
                            CreatedDate = new DateTime(2023, 5, 21, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9770),
                            Description = "Data miners"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Super Active",
                            CreatedDate = new DateTime(2023, 5, 6, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9773),
                            Description = "Minecraft Enjoyers"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Active",
                            CreatedDate = new DateTime(2023, 5, 11, 15, 6, 51, 268, DateTimeKind.Local).AddTicks(9775),
                            Description = "Starcraft Koreans"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
