// <auto-generated />
using System;
using AspCoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspCoreMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230516092853_AddFewUsers")]
    partial class AddFewUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspCoreMVC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 5, 14, 16, 28, 53, 427, DateTimeKind.Local).AddTicks(6393),
                            GroupId = 2,
                            Login = "boris2020",
                            Password = "123boris123",
                            UserState = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 5, 6, 16, 28, 53, 427, DateTimeKind.Local).AddTicks(6411),
                            GroupId = 1,
                            Login = "superadmin",
                            Password = "adminadmin1",
                            UserState = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 5, 13, 16, 28, 53, 427, DateTimeKind.Local).AddTicks(6413),
                            GroupId = 2,
                            Login = "serejenka",
                            Password = "imserge222",
                            UserState = "Blocked"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
